<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<test-results name="D:\Tuto Source\Delphi\DUnitX\Win32\Debug\Project4.exe" total="3" errors="0" failures="2" ignored="0" inconclusive="0" not-run="0" skipped="0" invalid="0" date="2019-08-21" time="0.003">
  <culture-info current-culture="en" current-uiculture="en" />
  <test-suite type="Assembly" name="Project4.exe" executed="true" result="Failure" success="False" time="0.003" asserts="0">
    <results>
        <test-suite type="Namespace" name="s" executed="true" result="Failure" success="False" time="0.001" asserts="0" >
          <results>
              <test-suite type="Fixture" name="TMyTestObject" executed="True" result="Failure" success="False" time="0.001" >
                <results>
                  <test-case name="Test1.TEST AAA 1111" executed="True" result="Failure" success="False" time="0.000" asserts="0" >
                    <failure>
                      <message>
                        <![CDATA[ Expected 6 but got 5  ]]>
                      </message>
                      <stack-trace>
                        <![CDATA[  ]]>
                      </stack-trace>
                    </failure>
                  </test-case>
                  <test-case name="Test2.1111111" executed="True" result="Success" success="True" time="0.000" asserts="0" />
                  <test-case name="Test2.222222" executed="True" result="Failure" success="False" time="0.000" asserts="0" >
                    <failure>
                      <message>
                        <![CDATA[ Expected 20 is not equal to actual 4  ]]>
                      </message>
                      <stack-trace>
                        <![CDATA[  ]]>
                      </stack-trace>
                    </failure>
                  </test-case>
                </results>
              </test-suite>
          </results>
        </test-suite>
    </results>
  </test-suite>
</test-results>
